modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/RainFoxStar/onlyGtmMultiblockRegister/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="gtceu"
    mandatory=false
    versionRange="[7.5.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ldlib"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

# JEI 只用于「多方块结构预览」这一个功能，没装也不影响注册与运行
[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[15.0.0,)"
    ordering="AFTER"
    side="BOTH"
